#ifndef UNIDOS_DEFS_H
#define UNIDOS_DEFS_H

// real-mode far pointer created from segment & offset
#define MK_FP(SEG, OFF) (((SEG) << 4) + (OFF))

#define MIN(a, b) ((a) < (b)? (a) : (b))
#define MAX(a, b) ((a) > (b)? (a) : (b))

#define ALIGN(a, b) (((a) + (b)) & ~((b) - 1))

enum DOS_ERROR
{
    ERR_SUCCESS = 0x00,
    ERR_INVALID_FUNCTION_NUMBER = 0x01,
    ERR_FILE_NOT_FOUND = 0x02,
    ERR_PATH_NOT_FOUND = 0x03,
    ERR_TOO_MANY_OPEN_FILES = 0x04,
    ERR_ACCESS_DENIED = 0x05,
    ERR_INVALID_HANDLE = 0x06,
    ERR_MEMORY_CONTROL_BLOCKS_DESTROYED = 0x07,
    ERR_INSUFFICIENT_MEMORY = 0x08,
    ERR_INVALID_MEMORY_BLOCK_ADDRESS = 0x09,
    ERR_INVALID_ENVIRONMENT = 0x0A,
    ERR_INVALID_FORMAT = 0x0B,
    ERR_INVALID_ACCESS_MODE = 0x0C,
    ERR_INVALID_DATA = 0x0D,
    ERR_RESERVED = 0x0E,
    ERR_INVALID_DRIVE_SPECIFIED = 0x0F,
    ERR_ATTEMPT_TO_REMOVE_CURRENT_DIRECTORY = 0x10,
    ERR_NOT_SAME_DEVICE = 0x11,
    ERR_NO_MORE_FILES = 0x12,
    ERR_ATTEMPT_TO_WRITE_ON_A_WRITE_PROTECTED_DISKETTE = 0x13,
    ERR_UNKNOWN_UNIT = 0x14,
    ERR_DRIVE_NOT_READY = 0x15,
    ERR_UNKNOWN_COMMAND = 0x16,
    ERR_CRC_ERROR = 0x17,
    ERR_BAD_REQUEST_STRUCTURE_LENGTH = 0x18,
    ERR_SEEK_ERROR = 0x19,
    ERR_UNKNOWN_MEDIA_TYPE = 0x1A,
    ERR_SECTOR_NOT_FOUND = 0x1B,
    ERR_PRINTER_OUT_OF_PAPER = 0x1C,
    ERR_WRITE_FAULT = 0x1D,
    ERR_READ_FAULT = 0x1E,
    ERR_GENERAL_FAILURE = 0x1F,
    ERR_SHARING_VIOLATION = 0x20,
    ERR_LOCK_VIOLATION = 0x21,
    ERR_INVALID_DISK_CHANGE = 0x22,
    ERR_FCB_UNAVAILABLE = 0x23,
    ERR_SHARING_BUFFER_OVERFLOW = 0x24,
    ERR_UNABLE_TO_COMPLETE_FILE_OPERATION = 0x26,
    ERR_NETWORK_REQUEST_NOT_SUPPORTED = 0x32,
    ERR_REMOTE_COMPUTER_NOT_LISTENING = 0x33,
    ERR_DUPLICATE_NAME_ON_NETWORK = 0x34,
    ERR_NETWORK_NAME_NOT_FOUND = 0x35,
    ERR_NETWORK_BUSY = 0x36,
    ERR_NETWORK_DEVICE_NO_LONGER_EXISTS = 0x37,
    ERR_NETBIOS_COMMAND_LIMIT_EXCEEDED = 0x38,
    ERR_NETWORK_ADAPTER_ERROR = 0x39,
    ERR_INCORRECT_NETWORK_RESPONSE = 0x3A,
    ERR_UNEXPECTED_NETWORK_ERROR = 0x3B,
    ERR_INCOMPATIBLE_REMOTE_ADAPTER = 0x3C,
    ERR_PRINT_QUEUE_FULL = 0x3D,
    ERR_NO_SPACE_FOR_PRINT_FILE = 0x3E,
    ERR_PRINT_FILE_DELETED = 0x3F,
    ERR_NETWORK_NAME_DELETED = 0x40,
    ERR_ACCESS_DENIED_2 = 0x41,
    ERR_NETWORK_DEVICE_TYPE_INCORRECT = 0x42,
    ERR_NETWORK_NAME_NOT_FOUND_2 = 0x43,
    ERR_NETWORK_NAME_LIMIT_EXCEEDED = 0x44,
    ERR_NETBIOS_SESSION_LIMIT_EXCEEDED = 0x45,
    ERR_TEMPORARILY_PAUSED = 0x46,
    ERR_NETWORK_REQUEST_NOT_ACCEPTED = 0x47,
    ERR_PRINT_OR_DISK_REDIRECTION_IS_PAUSED = 0x48,
    ERR_FILE_ALREADY_EXISTS = 0x50,
    ERR_CANNOT_MAKE_DIRECTORY_ENTRY = 0x52,
    ERR_FAIL_ON_INT_24 = 0x53,
    ERR_TOO_MANY_REDIRECTIONS = 0x54,
    ERR_DUPLICATE_REDIRECTION = 0x55,
    ERR_INVALID_PASSWORD = 0x56,
    ERR_INVALID_PARAMETER = 0x57,
    ERR_NETWORK_DEVICE_FAULT = 0x58,
    ERR_FUNCTION_NOT_SUPPORTED_BY_NETWORK = 0x59,
    ERR_REQUIRED_SYSTEM_COMPONENT_NOT_INSTALLED = 0x5A
};

#endif